name: Ruby 3.2 docker image

on:
  push:
    branches: [ "main" ]
    paths:
      - '3.2/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '3.2/**'

jobs:
  build-80:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DK_HUB_USR }}
          password: ${{ secrets.DK_HUB }}

      - name: Build the Docker image for Ruby 3.2 with Ruby on Rails
        run: |
          make 32
          make 32 env=dev
